name: Build and publish new version to S3
on:
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'

      - name: Build tools
        run: |
          mkdir install
          cmake -S . -B build
          cmake --build build
          cmake --install build --prefix install
          chmod +x install/bin/mavdecode
          chmod +x install/bin/mavencode

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mavtools-linux-gnu-x86_64
          path: install/bin

      - name: Upload release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'release'
        run: |
          tar czf mavtools-linux-gnu-x86_64.tar.gz install/bin
          gh release upload ${{github.event.release.tag_name}} mavtools-linux-gnu-x86_64.tar.gz --clobber      

